#!/bin/tcsh

if ( "$1" == "" ) then      # parentheses not strictly needed in this simple case
    echo "variable 1 is empty = set it to the string-label"
    exit
else 
    echo "variable contains $1"
endif

hadd $1_all_0.root convert_00??_run/event_?00.root
hadd $1_all_1.root convert_01??_run/event_?00.root
hadd $1_all_2.root convert_02??_run/event_?00.root
hadd $1_all_3.root convert_03??_run/event_?00.root
hadd $1_all_4.root convert_04??_run/event_?00.root
hadd $1_all_5.root convert_05??_run/event_?00.root
hadd $1_all_6.root convert_06??_run/event_?00.root
hadd $1_all_7.root convert_07??_run/event_?00.root
hadd $1_all_8.root convert_08??_run/event_?00.root
hadd $1_all_9.root convert_09??_run/event_?00.root 
hadd $1_all_10.root convert_10??_run/event_?00.root
hadd $1_all_11.root convert_11??_run/event_?00.root
hadd $1_all_12.root convert_12??_run/event_?00.root
hadd $1_all_13.root convert_13??_run/event_?00.root
hadd $1_all_14.root convert_14??_run/event_?00.root
hadd $1_all_15.root convert_15??_run/event_?00.root
hadd $1_all_16.root convert_16??_run/event_?00.root
hadd $1_all_17.root convert_17??_run/event_?00.root
hadd $1_all_18.root convert_18??_run/event_?00.root
hadd $1_all_19.root convert_19??_run/event_?00.root 
hadd $1_all_20.root convert_20??_run/event_?00.root
hadd $1_all_21.root convert_21??_run/event_?00.root
hadd $1_all_22.root convert_22??_run/event_?00.root
hadd $1_all_23.root convert_23??_run/event_?00.root
hadd $1_all_24.root convert_24??_run/event_?00.root
hadd $1_all_25.root convert_25??_run/event_?00.root
hadd $1_all_26.root convert_26??_run/event_?00.root
hadd $1_all_27.root convert_27??_run/event_?00.root
hadd $1_all_28.root convert_28??_run/event_?00.root
hadd $1_all_29.root convert_29??_run/event_?00.root 
hadd $1_all_30.root convert_30??_run/event_?00.root
hadd $1_all_31.root convert_31??_run/event_?00.root
hadd $1_all_32.root convert_32??_run/event_?00.root
hadd $1_all_33.root convert_33??_run/event_?00.root
hadd $1_all_34.root convert_34??_run/event_?00.root
hadd $1_all_35.root convert_35??_run/event_?00.root
hadd $1_all_36.root convert_36??_run/event_?00.root
hadd $1_all_37.root convert_37??_run/event_?00.root
hadd $1_all_38.root convert_38??_run/event_?00.root
hadd $1_all_39.root convert_39??_run/event_?00.root 
hadd $1_all_40.root convert_40??_run/event_?00.root
hadd $1_all_41.root convert_41??_run/event_?00.root
hadd $1_all_42.root convert_42??_run/event_?00.root
hadd $1_all_43.root convert_43??_run/event_?00.root
hadd $1_all_44.root convert_44??_run/event_?00.root
hadd $1_all_45.root convert_45??_run/event_?00.root
hadd $1_all_46.root convert_46??_run/event_?00.root
hadd $1_all_47.root convert_47??_run/event_?00.root
hadd $1_all_48.root convert_48??_run/event_?00.root
hadd $1_all_49.root convert_49??_run/event_?00.root 
hadd $1_all_50.root convert_50??_run/event_?00.root
hadd $1_all_51.root convert_51??_run/event_?00.root
hadd $1_all_52.root convert_52??_run/event_?00.root
hadd $1_all_53.root convert_53??_run/event_?00.root
hadd $1_all_54.root convert_54??_run/event_?00.root
hadd $1_all_55.root convert_55??_run/event_?00.root
hadd $1_all_56.root convert_56??_run/event_?00.root
hadd $1_all_57.root convert_57??_run/event_?00.root
hadd $1_all_58.root convert_58??_run/event_?00.root
hadd $1_all_59.root convert_59??_run/event_?00.root 
hadd $1_all_60.root convert_60??_run/event_?00.root
hadd $1_all_61.root convert_61??_run/event_?00.root
hadd $1_all_62.root convert_62??_run/event_?00.root
hadd $1_all_63.root convert_63??_run/event_?00.root
hadd $1_all_64.root convert_64??_run/event_?00.root
hadd $1_all_65.root convert_65??_run/event_?00.root
hadd $1_all_66.root convert_66??_run/event_?00.root
hadd $1_all_67.root convert_67??_run/event_?00.root
hadd $1_all_68.root convert_68??_run/event_?00.root
hadd $1_all_69.root convert_69??_run/event_?00.root 
hadd $1_all_70.root convert_70??_run/event_?00.root
hadd $1_all_71.root convert_71??_run/event_?00.root
hadd $1_all_72.root convert_72??_run/event_?00.root
hadd $1_all_73.root convert_73??_run/event_?00.root
hadd $1_all_74.root convert_74??_run/event_?00.root
hadd $1_all_75.root convert_75??_run/event_?00.root
hadd $1_all_76.root convert_76??_run/event_?00.root
hadd $1_all_77.root convert_77??_run/event_?00.root
hadd $1_all_78.root convert_78??_run/event_?00.root
hadd $1_all_79.root convert_79??_run/event_?00.root 
hadd $1_all_80.root convert_80??_run/event_?00.root
hadd $1_all_81.root convert_81??_run/event_?00.root
hadd $1_all_82.root convert_82??_run/event_?00.root
hadd $1_all_83.root convert_83??_run/event_?00.root
hadd $1_all_84.root convert_84??_run/event_?00.root
hadd $1_all_85.root convert_85??_run/event_?00.root
hadd $1_all_86.root convert_86??_run/event_?00.root
hadd $1_all_87.root convert_87??_run/event_?00.root
hadd $1_all_88.root convert_88??_run/event_?00.root
hadd $1_all_89.root convert_89??_run/event_?00.root 
hadd $1_all_90.root convert_90??_run/event_?00.root
hadd $1_all_91.root convert_91??_run/event_?00.root
hadd $1_all_92.root convert_92??_run/event_?00.root
hadd $1_all_93.root convert_93??_run/event_?00.root
hadd $1_all_94.root convert_94??_run/event_?00.root
hadd $1_all_95.root convert_95??_run/event_?00.root
hadd $1_all_96.root convert_96??_run/event_?00.root
hadd $1_all_97.root convert_97??_run/event_?00.root
hadd $1_all_98.root convert_98??_run/event_?00.root
hadd $1_all_99.root convert_99??_run/event_?00.root  convert_10000_run/event_?00.root





