Universe       = vanilla
Notification   = Error
GetEnv         = True
Initialdir     = $ENV(PWD)
Executable     = /bin/csh
Arguments      = $ENV(PWD)/runamptana_b0_2.csh $(process)
Log            = $ENV(PWD)/logs/log_b0_2/myprog$(process).log
Output         = $ENV(PWD)/logs/log_b0_2/myprog$(process).out
Error          = $ENV(PWD)/logs/log_b0_2/myprog$(process).log
+Experiment    = "star"
+Job_Type      = "cas"
Queue 100

