Version: 1.8 # minimal SMASH version to use with this config file

Logging:
    default: INFO

General:
    Modus:          Collider
    Time_Step_Mode: Fixed
    Delta_Time:     0.1
    End_Time:       200.0
    Randomseed:     -1
    Nevents:        100

Output:
    Output_Interval: 10.0
    Particles:
        Format:          ["Oscar2013"]
        Extended: True
Modi:
    Collider:
        Projectile:
            Particles: {2212: 79, 2112: 118} #Gold197
        Target:
            Particles: {2212: 79, 2112: 118} #Gold197
        Impact:
            Sample: "quadratic"
            Range: [5.0, 9.0]
        Sqrtsnn: 3.0
        Fermi_Motion: "on"
        Collisions_Within_Nucleus: False
#        Fermi_Motion: "frozen"
#        E_Kin: 1.23

Potentials:
    VDF:
        Sat_rhoB: 0.160
        Powers: [1.7681391, 3.5293515, 5.4352788, 6.3809822]
        Coeffs: [-8.450948e+01, 3.843139e+01, -7.958557e+00, 1.552594e+00]
