#!/bin/tcsh
if($1 == 0) ./doit3 3 1 -1
if($1 == 1) ./doit3 3 2 -1
if($1 == 2) ./doit3 5 1 -1
if($1 == 3) ./doit3 5 2 -1
if($1 == 4) ./doit3 8 1 -1
if($1 == 5) ./doit3 8 2 -1
if($1 == 6) ./doit3 19 1 -1
if($1 == 8) ./doit3 200 8500
if($1 == 9) ./doit3 200 2 9000
if($1 == 7)  echo "19melt got deleted"
